//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ACAO
    {
        public TB_ACAO()
        {
            this.TB_GRUPO_NOTIFICACAO_ACAO = new HashSet<TB_GRUPO_NOTIFICACAO_ACAO>();
        }
    
        public int ID { get; set; }
        public int ID_TIPO_ACAO { get; set; }
        public int ID_TAREFA { get; set; }
        public string NOM_CAMINHO_APP { get; set; }
        public string DES_ARGUMENTO { get; set; }
        public int NUM_ORDEM_EXECUCAO { get; set; }
    
        public virtual TB_TAREFA TB_TAREFA { get; set; }
        public virtual TB_TIPO_ACAO TB_TIPO_ACAO { get; set; }
        public virtual ICollection<TB_GRUPO_NOTIFICACAO_ACAO> TB_GRUPO_NOTIFICACAO_ACAO { get; set; }
    }
}
