//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONTROLER
    {
        public TB_CONTROLER()
        {
            this.TB_ACTION = new HashSet<TB_ACTION>();
        }
    
        public int ID { get; set; }
        public string NOM_CONTROLLER { get; set; }
    
        public virtual ICollection<TB_ACTION> TB_ACTION { get; set; }
    }
}
