//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE
    {
        public TB_CLIENTE()
        {
            this.TB_DEPARTAMENTO_CLIENTE = new HashSet<TB_DEPARTAMENTO_CLIENTE>();
            this.TB_UNIDADE = new HashSet<TB_UNIDADE>();
        }
    
        public int ID { get; set; }
        public int ID_TIPO_PESSOA { get; set; }
        public string NOM_FANTASIA { get; set; }
        public string NOM_RAZAO { get; set; }
        public string NUM_DOCUMENTO { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual TB_TIPO_PESSOA TB_TIPO_PESSOA { get; set; }
        public virtual ICollection<TB_DEPARTAMENTO_CLIENTE> TB_DEPARTAMENTO_CLIENTE { get; set; }
        public virtual ICollection<TB_UNIDADE> TB_UNIDADE { get; set; }
    }
}
