//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONTATO
    {
        public int ID { get; set; }
        public int TB_TIPO_CONTATO_ID { get; set; }
        public int ID_UNIDADE { get; set; }
        public string DES_CONTATO { get; set; }
        public string NOM_CONTATO { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual TB_UNIDADE TB_UNIDADE { get; set; }
        public virtual TB_TIPO_CONTATO TB_TIPO_CONTATO { get; set; }
    }
}
