//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEPARTAMENTO_CLIENTE
    {
        public TB_DEPARTAMENTO_CLIENTE()
        {
            this.TB_FONTE_DEPARTAMENTO = new HashSet<TB_FONTE_DEPARTAMENTO>();
            this.TB_MODULO_DEPARTAMENTO = new HashSet<TB_MODULO_DEPARTAMENTO>();
            this.TB_USUARIO = new HashSet<TB_USUARIO>();
        }
    
        public int ID { get; set; }
        public int ID_CLIENTE { get; set; }
        public string NOM_DEPARTAMENTO { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual ICollection<TB_FONTE_DEPARTAMENTO> TB_FONTE_DEPARTAMENTO { get; set; }
        public virtual ICollection<TB_MODULO_DEPARTAMENTO> TB_MODULO_DEPARTAMENTO { get; set; }
        public virtual ICollection<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
