//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DISPARADOR
    {
        public TB_DISPARADOR()
        {
            this.TB_AGENDA_EXECUCAO = new HashSet<TB_AGENDA_EXECUCAO>();
        }
    
        public int ID { get; set; }
        public int ID_TIPO_DISPARADOR { get; set; }
        public int ID_TAREFA { get; set; }
        public System.DateTime DTH_INICIO { get; set; }
        public Nullable<System.DateTime> DTH_FIM { get; set; }
        public Nullable<bool> FLG_DOMINGO { get; set; }
        public Nullable<bool> FLG_SEGUNDA { get; set; }
        public Nullable<bool> FLG_TERCA { get; set; }
        public Nullable<bool> FLG_QUARTA { get; set; }
        public Nullable<bool> FLG_QUINTA { get; set; }
        public Nullable<bool> FLG_SEXTA { get; set; }
        public Nullable<bool> FLG_SABADO { get; set; }
        public int NUM_REPETICAO { get; set; }
    
        public virtual ICollection<TB_AGENDA_EXECUCAO> TB_AGENDA_EXECUCAO { get; set; }
        public virtual TB_TAREFA TB_TAREFA { get; set; }
        public virtual TB_TIPO_DISPARADOR TB_TIPO_DISPARADOR { get; set; }
    }
}
