//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ENDERECO
    {
        public int ID { get; set; }
        public int TB_CIDADE_ID { get; set; }
        public int ID_TIPO_LOGRADOURO { get; set; }
        public int ID_UNIDADE { get; set; }
        public string DES_ENDERECO { get; set; }
        public string DES_NUMERO_ALTURA { get; set; }
        public string DES_COMPLEMENTO { get; set; }
    
        public virtual TB_CIDADE TB_CIDADE { get; set; }
        public virtual TB_TIPO_LOGRADOURO TB_TIPO_LOGRADOURO { get; set; }
        public virtual TB_UNIDADE TB_UNIDADE { get; set; }
    }
}
