//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FONTE_PAGADORA_PARAMETRO
    {
        public TB_FONTE_PAGADORA_PARAMETRO()
        {
            this.TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO = new HashSet<TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO>();
        }
    
        public int ID { get; set; }
        public string NOM_PARAMETRO { get; set; }
    
        public virtual ICollection<TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO> TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO { get; set; }
    }
}
