//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO
    {
        public TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO()
        {
            this.TB_TAREFA_FONTE_ACESSO = new HashSet<TB_TAREFA_FONTE_ACESSO>();
        }
    
        public int ID { get; set; }
        public int ID_FONTE_PAGADORA_PARAMETRO { get; set; }
        public int ID_FONTE_PAGADORA { get; set; }
    
        public virtual TB_FONTE_PAGADORA TB_FONTE_PAGADORA { get; set; }
        public virtual TB_FONTE_PAGADORA_PARAMETRO TB_FONTE_PAGADORA_PARAMETRO { get; set; }
        public virtual ICollection<TB_TAREFA_FONTE_ACESSO> TB_TAREFA_FONTE_ACESSO { get; set; }
    }
}
