//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GRUPO_NOTIFICACAO_ACAO
    {
        public int ID { get; set; }
        public int ID_GRUPO_NOTIFICACAO { get; set; }
        public int ID_ACAO { get; set; }
    
        public virtual TB_ACAO TB_ACAO { get; set; }
        public virtual TB_GRUPO_NOTIFICACAO TB_GRUPO_NOTIFICACAO { get; set; }
    }
}
