//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOG_SISTEMA
    {
        public int ID { get; set; }
        public int ID_ACTION { get; set; }
        public int ID_MODULO { get; set; }
        public int ID_USUARIO { get; set; }
        public System.DateTime DTH_ACAO { get; set; }
        public bool FLG_ERRO { get; set; }
        public string DES_ACAO { get; set; }
        public string NUM_IP { get; set; }
    
        public virtual TB_ACTION TB_ACTION { get; set; }
        public virtual TB_MODULO TB_MODULO { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
