//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MODULO_DEPARTAMENTO
    {
        public int ID { get; set; }
        public int ID_DEPARTAMENTO { get; set; }
        public int ID_MODULO { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual TB_DEPARTAMENTO_CLIENTE TB_DEPARTAMENTO_CLIENTE { get; set; }
        public virtual TB_MODULO TB_MODULO { get; set; }
    }
}
