//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MODULO
    {
        public TB_MODULO()
        {
            this.TB_LOG_SISTEMA = new HashSet<TB_LOG_SISTEMA>();
            this.TB_MODULO_DEPARTAMENTO = new HashSet<TB_MODULO_DEPARTAMENTO>();
            this.TB_TAREFA = new HashSet<TB_TAREFA>();
        }
    
        public int ID { get; set; }
        public string NOM_MODULO { get; set; }
        public string DES_MODULO { get; set; }
        public Nullable<bool> FLG_ATIVO { get; set; }
    
        public virtual ICollection<TB_LOG_SISTEMA> TB_LOG_SISTEMA { get; set; }
        public virtual ICollection<TB_MODULO_DEPARTAMENTO> TB_MODULO_DEPARTAMENTO { get; set; }
        public virtual ICollection<TB_TAREFA> TB_TAREFA { get; set; }
    }
}
