//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MENU
    {
        public TB_MENU()
        {
            this.TB_SUBMENU = new HashSet<TB_SUBMENU>();
        }
    
        public int ID { get; set; }
        public string NOM_MENU { get; set; }
        public int NUM_ORDEM { get; set; }
        public string NOM_IMAGEM { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual ICollection<TB_SUBMENU> TB_SUBMENU { get; set; }
    }
}
