//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_CONTATO
    {
        public TB_TIPO_CONTATO()
        {
            this.TB_CONTATO = new HashSet<TB_CONTATO>();
        }
    
        public int ID { get; set; }
        public string DES_CONTATO { get; set; }
        public string DES_MASCARA { get; set; }
    
        public virtual ICollection<TB_CONTATO> TB_CONTATO { get; set; }
    }
}
