//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_DISPARADOR
    {
        public TB_TIPO_DISPARADOR()
        {
            this.TB_DISPARADOR = new HashSet<TB_DISPARADOR>();
        }
    
        public int ID { get; set; }
        public string DES_TIPO { get; set; }
    
        public virtual ICollection<TB_DISPARADOR> TB_DISPARADOR { get; set; }
    }
}
