//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TAREFA_PROXIMA
    {
        public int ID { get; set; }
        public int ID_TAREFA_PROXIMA { get; set; }
        public int ID_TAREFA_ATUAL { get; set; }
    
        public virtual TB_TAREFA TB_TAREFA { get; set; }
        public virtual TB_TAREFA TB_TAREFA1 { get; set; }
    }
}
