//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_PESSOA
    {
        public TB_TIPO_PESSOA()
        {
            this.TB_CLIENTE = new HashSet<TB_CLIENTE>();
        }
    
        public int ID { get; set; }
        public string DES_PESSOA { get; set; }
    
        public virtual ICollection<TB_CLIENTE> TB_CLIENTE { get; set; }
    }
}
