//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_ENTREGA
    {
        public TB_TIPO_ENTREGA()
        {
            this.TB_TAREFA_TIPO_ENTREGA = new HashSet<TB_TAREFA_TIPO_ENTREGA>();
        }
    
        public int ID { get; set; }
        public string DES_TIPO_ENTREGA { get; set; }
        public Nullable<bool> FLG_ATIVO { get; set; }
    
        public virtual ICollection<TB_TAREFA_TIPO_ENTREGA> TB_TAREFA_TIPO_ENTREGA { get; set; }
    }
}
