//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TAREFA_TIPO_ENTREGA
    {
        public int ID { get; set; }
        public int TB_TIPO_ENTREGA_ID { get; set; }
        public int TB_TAREFA_ID { get; set; }
    
        public virtual TB_TAREFA TB_TAREFA { get; set; }
        public virtual TB_TIPO_ENTREGA TB_TIPO_ENTREGA { get; set; }
    }
}
