//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_NOTIFICACAO
    {
        public TB_TIPO_NOTIFICACAO()
        {
            this.TB_GRUPO_NOTIFICACAO = new HashSet<TB_GRUPO_NOTIFICACAO>();
        }
    
        public int ID { get; set; }
        public string DES_NOTIFICACAO { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual ICollection<TB_GRUPO_NOTIFICACAO> TB_GRUPO_NOTIFICACAO { get; set; }
    }
}
