//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TAREFA
    {
        public TB_TAREFA()
        {
            this.TB_ACAO = new HashSet<TB_ACAO>();
            this.TB_DISPARADOR = new HashSet<TB_DISPARADOR>();
            this.TB_HISTORICO_EXECUCAO = new HashSet<TB_HISTORICO_EXECUCAO>();
            this.TB_TAREFA_FONTE = new HashSet<TB_TAREFA_FONTE>();
            this.TB_TAREFA_PROXIMA = new HashSet<TB_TAREFA_PROXIMA>();
            this.TB_TAREFA_PROXIMA1 = new HashSet<TB_TAREFA_PROXIMA>();
            this.TB_TAREFA_TIPO_ENTREGA = new HashSet<TB_TAREFA_TIPO_ENTREGA>();
        }
    
        public int ID { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_MODULO { get; set; }
        public string NOM_TAREFA { get; set; }
        public string DES_TAREFA { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual ICollection<TB_ACAO> TB_ACAO { get; set; }
        public virtual ICollection<TB_DISPARADOR> TB_DISPARADOR { get; set; }
        public virtual ICollection<TB_HISTORICO_EXECUCAO> TB_HISTORICO_EXECUCAO { get; set; }
        public virtual TB_MODULO TB_MODULO { get; set; }
        public virtual ICollection<TB_TAREFA_FONTE> TB_TAREFA_FONTE { get; set; }
        public virtual ICollection<TB_TAREFA_PROXIMA> TB_TAREFA_PROXIMA { get; set; }
        public virtual ICollection<TB_TAREFA_PROXIMA> TB_TAREFA_PROXIMA1 { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        public virtual ICollection<TB_TAREFA_TIPO_ENTREGA> TB_TAREFA_TIPO_ENTREGA { get; set; }
    }
}
