//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TAREFA_FONTE_ACESSO
    {
        public int ID { get; set; }
        public int ID_UNIDADE { get; set; }
        public int ID_FONTE_PARAMETRO_DEFINICAO { get; set; }
        public int ID_TAREFA_FONTE { get; set; }
        public string VAL_ACESSO { get; set; }
    
        public virtual TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO { get; set; }
        public virtual TB_TAREFA_FONTE TB_TAREFA_FONTE { get; set; }
        public virtual TB_UNIDADE TB_UNIDADE { get; set; }
    }
}
