//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.younityOne.DAL.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public TB_USUARIO()
        {
            this.TB_LOG_ACESSO = new HashSet<TB_LOG_ACESSO>();
            this.TB_LOG_SISTEMA = new HashSet<TB_LOG_SISTEMA>();
            this.TB_TAREFA = new HashSet<TB_TAREFA>();
            this.TB_USUARIO_ACTION = new HashSet<TB_USUARIO_ACTION>();
        }
    
        public int ID { get; set; }
        public int ID_DEPARTAMENTO { get; set; }
        public int ID_GRUPO { get; set; }
        public string COD_USUARIO { get; set; }
        public string DES_SENHA { get; set; }
        public string NOM_USUARIO { get; set; }
        public string NUM_CPF { get; set; }
        public string END_MAIL { get; set; }
        public bool FLG_ATIVO { get; set; }
    
        public virtual TB_DEPARTAMENTO_CLIENTE TB_DEPARTAMENTO_CLIENTE { get; set; }
        public virtual ICollection<TB_LOG_ACESSO> TB_LOG_ACESSO { get; set; }
        public virtual ICollection<TB_LOG_SISTEMA> TB_LOG_SISTEMA { get; set; }
        public virtual ICollection<TB_TAREFA> TB_TAREFA { get; set; }
        public virtual TB_USUARIO_GRUPO TB_USUARIO_GRUPO { get; set; }
        public virtual ICollection<TB_USUARIO_ACTION> TB_USUARIO_ACTION { get; set; }
    }
}
