USE YOUNITY_ONE
GO

INSERT INTO TB_TIPO_PESSOA (DES_PESSOA) VALUES ('FISICA')
INSERT INTO TB_TIPO_PESSOA (DES_PESSOA) VALUES ('JURIDICA')
GO

INSERT INTO TB_CLIENTE
	(ID_TIPO_PESSOA, NOM_FANTASIA, NOM_RAZAO, NUM_DOCUMENTO, FLG_ATIVO)
VALUES
	(1,'DASA', 'DASA', '01234567000102', 1)

INSERT INTO TB_DEPARTAMENTO_CLIENTE
	(ID_CLIENTE, NOM_DEPARTAMENTO, FLG_ATIVO)
VALUES
	(1, 'GERENCIA CONTAS RECEBER', 1)


INSERT INTO TB_USUARIO_GRUPO
	(DES_GRUPO, FLG_ATIVO)
VALUES
	('Administrador', 1)

INSERT INTO TB_USUARIO
	(ID_DEPARTAMENTO, ID_GRUPO, COD_USUARIO, DES_SENHA, NOM_USUARIO, NUM_CPF, END_MAIL, FLG_ATIVO)
VALUES
	(1, 1, '033004221', '123456', 'RENATO', '30579879828', 'renato@younitytec.com.br', 1)


INSERT INTO TB_CONTROLER
	(NOM_CONTROLLER)
VALUES
	('Dashboards')

INSERT INTO TB_ACTION
	(ID_CONTROLLER, NOM_ACTION)
VALUES
	(1, 'Dashboard_1')


INSERT INTO TB_PERMISSOES_GRUPO
	(ID_ACTION, ID_GRUPO)
VALUES
	(1, 1)