USE master
GO

EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'YOUNITY_ONE'
GO
USE [master]
GO
ALTER DATABASE [YOUNITY_ONE] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
/****** Object:  Database [YOUNITY_ONE]    Script Date: 28/10/2016 21:54:25 ******/
DROP DATABASE [YOUNITY_ONE]
GO


CREATE DATABASE YOUNITY_ONE
GO

USE YOUNITY_ONE
GO

CREATE TABLE TB_TIPO_ACAO (
  ID INTEGER  NOT NULL   IDENTITY ,
  DES_TIPO VARCHAR(100)  NOT NULL    ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_TIPO_CONTATO (
  ID INTEGER  NOT NULL   IDENTITY ,
  DES_CONTATO VARCHAR(300)  NOT NULL  ,
  DES_MASCARA VARCHAR(600)      ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_MODULO (
  ID INTEGER  NOT NULL   IDENTITY ,
  NOM_MODULO VARCHAR(300)  NOT NULL  ,
  DES_MODULO VARCHAR(1000)  NOT NULL  ,
  FLG_ATIVO BIT      ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_FONTE_PAGADORA_PARAMETRO (
  ID INTEGER  NOT NULL   IDENTITY ,
  NOM_PARAMETRO VARCHAR(300)      ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_MENU (
  ID INTEGER  NOT NULL   IDENTITY ,
  NOM_MENU VARCHAR(300)  NOT NULL  ,
  NUM_ORDEM INTEGER  NOT NULL  ,
  NOM_IMAGEM VARCHAR(300) NOT NULL    ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)  );
GO


CREATE UNIQUE INDEX UK_MENU ON TB_MENU (NOM_MENU);
GO



CREATE TABLE TB_TIPO_DISPARADOR (
  ID INT  NOT NULL   IDENTITY ,
  DES_TIPO VARCHAR(100)  NOT NULL    ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_TIPO_PESSOA (
  ID INTEGER  NOT NULL   IDENTITY ,
  DES_PESSOA VARCHAR(100)  NOT NULL    ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_USUARIO_GRUPO (
  ID INTEGER  NOT NULL   IDENTITY ,
  DES_GRUPO VARCHAR(300)  NOT NULL  ,
  FLG_ATIVO BIT      ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_TIPO_NOTIFICACAO (
  ID INTEGER  NOT NULL   IDENTITY ,
  DES_NOTIFICACAO VARCHAR(1000)  NOT NULL  ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_TIPO_ENTREGA (
  ID INTEGER  NOT NULL   IDENTITY ,
  DES_TIPO_ENTREGA VARCHAR(300)    ,
  FLG_ATIVO BIT      ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_TIPO_LOGRADOURO (
  ID INTEGER  NOT NULL   IDENTITY ,
  DES_LOGRADOURO VARCHAR(100)      ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_FONTE_PAGADORA (
  ID INTEGER  NOT NULL   IDENTITY ,
  NOM_FONTE VARCHAR(300)  NOT NULL  ,
  END_SITE VARCHAR(1000)  NOT NULL  ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_CIDADE (
  ID INTEGER  NOT NULL   IDENTITY ,
  NOM_CIDADE VARCHAR(2000)    ,
  SIG_UF VARCHAR(2)      ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_CONTROLER (
  ID INTEGER  NOT NULL   IDENTITY ,
  NOM_CONTROLLER VARCHAR(255)  NOT NULL    ,
PRIMARY KEY(ID));
GO



CREATE TABLE TB_ACTION (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_CONTROLLER INTEGER  NOT NULL  ,
  NOM_ACTION VARCHAR(255)  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_CONTROLLER)
    REFERENCES TB_CONTROLER(ID));
GO


CREATE INDEX TB_ACTION_FKIndex1 ON TB_ACTION (ID_CONTROLLER);
GO

CREATE INDEX IFK_FK_ACTION_CONTROLLER ON TB_ACTION (ID_CONTROLLER);
GO


CREATE TABLE TB_CLIENTE (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_TIPO_PESSOA INTEGER  NOT NULL  ,
  NOM_FANTASIA VARCHAR(400)  NOT NULL  ,
  NOM_RAZAO VARCHAR(1000)  NOT NULL  ,
  NUM_DOCUMENTO VARCHAR(50)  NOT NULL  ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_TIPO_PESSOA)
    REFERENCES TB_TIPO_PESSOA(ID));
GO


CREATE INDEX TB_CLIENTE_FKIndex1 ON TB_CLIENTE (ID_TIPO_PESSOA);
GO

CREATE INDEX IFK_FK_CLIENTE_TIPO_PESSOA ON TB_CLIENTE (ID_TIPO_PESSOA);
GO


CREATE TABLE TB_UNIDADE (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_CLIENTE INTEGER  NOT NULL  ,
  NUM_CNPJ VARCHAR(20)    ,
  NOM_UNIDADE VARCHAR(300)  NOT NULL  ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_CLIENTE)
    REFERENCES TB_CLIENTE(ID));
GO


CREATE INDEX TB_UNIDADE_FKIndex1 ON TB_UNIDADE (ID_CLIENTE);
GO

CREATE INDEX IFK_FK_UNIDADE_CLIENTE ON TB_UNIDADE (ID_CLIENTE);
GO


CREATE TABLE TB_GRUPO_NOTIFICACAO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_TIPO_NOTIFICACAO INTEGER  NOT NULL  ,
  DES_GRUPO VARCHAR(1000)      ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_TIPO_NOTIFICACAO)
    REFERENCES TB_TIPO_NOTIFICACAO(ID));
GO


CREATE INDEX TB_ACAO_GRUPO_NOTIFICACAO_FKIndex1 ON TB_GRUPO_NOTIFICACAO (ID_TIPO_NOTIFICACAO);
GO

CREATE INDEX IFK_FK_GRUPO_NOTIFICACAO_TIPO ON TB_GRUPO_NOTIFICACAO (ID_TIPO_NOTIFICACAO);
GO


CREATE TABLE TB_GRUPO_NOTIFICACAO_REMETENTE (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_GRUPO_NOTIFICACAO INTEGER  NOT NULL  ,
  NOM_REMETENTE VARCHAR(300)  NOT NULL  ,
  NUM_TELEFONE VARCHAR(100)    ,
  END_MAIL VARCHAR(4000)    ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_GRUPO_NOTIFICACAO)
    REFERENCES TB_GRUPO_NOTIFICACAO(ID));
GO


CREATE INDEX TB_GRUPO_NOTIFICACAO_REMETENTE_FKIndex1 ON TB_GRUPO_NOTIFICACAO_REMETENTE (ID_GRUPO_NOTIFICACAO);
GO

CREATE INDEX IFK_FK_GRUPO_NOTIFICACAO_REMET ON TB_GRUPO_NOTIFICACAO_REMETENTE (ID_GRUPO_NOTIFICACAO);
GO


CREATE TABLE TB_CONTATO (
  ID INTEGER  NOT NULL   IDENTITY ,
  TB_TIPO_CONTATO_ID INTEGER  NOT NULL  ,
  ID_UNIDADE INTEGER  NOT NULL  ,
  DES_CONTATO VARCHAR(1000)  NOT NULL  ,
  NOM_CONTATO VARCHAR(300)    ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES TB_UNIDADE(ID),
  FOREIGN KEY(TB_TIPO_CONTATO_ID)
    REFERENCES TB_TIPO_CONTATO(ID));
GO


CREATE INDEX TB_CONTATO_FKIndex1 ON TB_CONTATO (ID_UNIDADE);
GO
CREATE INDEX TB_CONTATO_FKIndex2 ON TB_CONTATO (TB_TIPO_CONTATO_ID);
GO

CREATE INDEX IFK_FK_UNIDADECONTATO ON TB_CONTATO (ID_UNIDADE);
GO
CREATE INDEX IFK_FK_CONTATO_TIPO ON TB_CONTATO (TB_TIPO_CONTATO_ID);
GO


CREATE TABLE TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_FONTE_PAGADORA_PARAMETRO INTEGER  NOT NULL  ,
  ID_FONTE_PAGADORA INTEGER  NOT NULL    ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_FONTE_PAGADORA)
    REFERENCES TB_FONTE_PAGADORA(ID),
  FOREIGN KEY(ID_FONTE_PAGADORA_PARAMETRO)
    REFERENCES TB_FONTE_PAGADORA_PARAMETRO(ID));
GO


CREATE INDEX TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO_FKIndex1 ON TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO (ID_FONTE_PAGADORA);
GO
CREATE INDEX TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO_FKIndex2 ON TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO (ID_FONTE_PAGADORA_PARAMETRO);
GO
CREATE UNIQUE INDEX UK_FONTE_PAGADORA_PARAMETRO_DEFINICAO ON TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO (ID_FONTE_PAGADORA_PARAMETRO, ID_FONTE_PAGADORA);
GO

CREATE INDEX IFK_FK_PARAM_DEFINICAO_FONTE ON TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO (ID_FONTE_PAGADORA);
GO
CREATE INDEX IFK_FK_PARAM_DEFINICAO_PARAMET ON TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO (ID_FONTE_PAGADORA_PARAMETRO);
GO


CREATE TABLE TB_SUBMENU (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_ACTION INTEGER  NOT NULL  ,
  ID_MENU INTEGER  NOT NULL  ,
  NOM_SUBMENU VARCHAR(300)  NOT NULL  ,
  NUM_ORDEM INTEGER  NOT NULL    ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_MENU)
    REFERENCES TB_MENU(ID),
  FOREIGN KEY(ID_ACTION)
    REFERENCES TB_ACTION(ID));
GO


CREATE INDEX TB_SUBMENU_FKIndex1 ON TB_SUBMENU (ID_MENU);
GO
CREATE INDEX TB_SUBMENU_FKIndex2 ON TB_SUBMENU (ID_ACTION);
GO

CREATE INDEX IFK_FK_SUBMENU_MENU ON TB_SUBMENU (ID_MENU);
GO
CREATE INDEX IFK_FK_SUBMENU_ACTION ON TB_SUBMENU (ID_ACTION);
GO


CREATE TABLE TB_PERMISSOES_GRUPO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_ACTION INTEGER  NOT NULL  ,
  ID_GRUPO INTEGER  NOT NULL    ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_GRUPO)
    REFERENCES TB_USUARIO_GRUPO(ID),
  FOREIGN KEY(ID_ACTION)
    REFERENCES TB_ACTION(ID));
GO


CREATE INDEX TB_PERMISSOES_GRUPO_FKIndex1 ON TB_PERMISSOES_GRUPO (ID_GRUPO);
GO
CREATE INDEX TB_PERMISSOES_GRUPO_FKIndex2 ON TB_PERMISSOES_GRUPO (ID_ACTION);
GO
CREATE UNIQUE INDEX UK_PERMISSOES_GRUPO ON TB_PERMISSOES_GRUPO (ID_ACTION, ID_GRUPO);
GO

CREATE INDEX IFK_FK_PERMISSOES_GRUPO ON TB_PERMISSOES_GRUPO (ID_GRUPO);
GO
CREATE INDEX IFK_FK_PERMISSOES_ACTION ON TB_PERMISSOES_GRUPO (ID_ACTION);
GO


CREATE TABLE TB_ENDERECO (
  ID INTEGER  NOT NULL   IDENTITY ,
  TB_CIDADE_ID INTEGER  NOT NULL  ,
  ID_TIPO_LOGRADOURO INTEGER  NOT NULL  ,
  ID_UNIDADE INTEGER  NOT NULL  ,
  DES_ENDERECO VARCHAR(1000)  NOT NULL  ,
  DES_NUMERO_ALTURA VARCHAR(100)  NOT NULL  ,
  DES_COMPLEMENTO VARCHAR(1000)      ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES TB_UNIDADE(ID),
  FOREIGN KEY(ID_TIPO_LOGRADOURO)
    REFERENCES TB_TIPO_LOGRADOURO(ID),
  FOREIGN KEY(TB_CIDADE_ID)
    REFERENCES TB_CIDADE(ID));
GO


CREATE INDEX TB_ENDERECO_FKIndex1 ON TB_ENDERECO (ID_UNIDADE);
GO
CREATE INDEX TB_ENDERECO_FKIndex2 ON TB_ENDERECO (ID_TIPO_LOGRADOURO);
GO
CREATE INDEX TB_ENDERECO_FKIndex3 ON TB_ENDERECO (TB_CIDADE_ID);
GO

CREATE INDEX IFK_FK_ENDERECO_UNIDADE ON TB_ENDERECO (ID_UNIDADE);
GO
CREATE INDEX IFK_FK_ENDERECO_TIPO_LOGRADOUR ON TB_ENDERECO (ID_TIPO_LOGRADOURO);
GO
CREATE INDEX IFK_FK_ENDERECO_CIDADE ON TB_ENDERECO (TB_CIDADE_ID);
GO


CREATE TABLE TB_DEPARTAMENTO_CLIENTE (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_CLIENTE INTEGER  NOT NULL  ,
  NOM_DEPARTAMENTO VARCHAR(500)  NOT NULL  ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_CLIENTE)
    REFERENCES TB_CLIENTE(ID));
GO


CREATE INDEX TB_DEPARTAMENTO_CLIENTE_FKIndex1 ON TB_DEPARTAMENTO_CLIENTE (ID_CLIENTE);
GO

CREATE INDEX IFK_FK_DEPARTAMENTO_CLIENTE ON TB_DEPARTAMENTO_CLIENTE (ID_CLIENTE);
GO


CREATE TABLE TB_USUARIO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_DEPARTAMENTO INTEGER  NOT NULL  ,
  ID_GRUPO INTEGER  NOT NULL  ,
  COD_USUARIO VARCHAR(15)  NOT NULL  ,
  DES_SENHA VARCHAR(4000)    ,
  NOM_USUARIO VARCHAR(200)  NOT NULL  ,
  NUM_CPF VARCHAR(11)  NOT NULL  ,
  END_MAIL VARCHAR(200)  NOT NULL  ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_GRUPO)
    REFERENCES TB_USUARIO_GRUPO(ID),
  FOREIGN KEY(ID_DEPARTAMENTO)
    REFERENCES TB_DEPARTAMENTO_CLIENTE(ID));
GO


CREATE INDEX TB_USUARIO_FKIndex1 ON TB_USUARIO (ID_GRUPO);
GO
CREATE INDEX TB_USUARIO_FKIndex2 ON TB_USUARIO (ID_DEPARTAMENTO);
GO
CREATE UNIQUE INDEX UK_TB_USUARIO ON TB_USUARIO (ID_DEPARTAMENTO, ID_GRUPO, COD_USUARIO);
GO

CREATE INDEX IFK_FK_USUARIO_GRUPO ON TB_USUARIO (ID_GRUPO);
GO
CREATE INDEX IFK_FK_DEPARTAMENTO_CLIENTE ON TB_USUARIO (ID_DEPARTAMENTO);
GO


CREATE TABLE TB_USUARIO_ACTION (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_USUARIO INTEGER  NOT NULL  ,
  ID_ACTION INTEGER  NOT NULL    ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_USUARIO)
    REFERENCES TB_USUARIO(ID),
  FOREIGN KEY(ID_ACTION)
    REFERENCES TB_ACTION(ID));
GO


CREATE INDEX TB_USUARIO_ACTION_FKIndex1 ON TB_USUARIO_ACTION (ID_USUARIO);
GO
CREATE INDEX TB_USUARIO_ACTION_FKIndex2 ON TB_USUARIO_ACTION (ID_ACTION);
GO
CREATE UNIQUE INDEX UK_USUARIO_ACTION ON TB_USUARIO_ACTION (ID_USUARIO, ID_ACTION);
GO

CREATE INDEX IFK_FK_USUARIO_ACTION_USUARIO ON TB_USUARIO_ACTION (ID_USUARIO);
GO
CREATE INDEX IFK_FK_USUARIO_ACTION_ACTION ON TB_USUARIO_ACTION (ID_ACTION);
GO


CREATE TABLE TB_LOG_ACESSO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_ACTION INTEGER  NOT NULL  ,
  ID_USUARIO INTEGER  NOT NULL  ,
  DTH_ACAO DATETIME    ,
  NUM_IP VARCHAR(50)      ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ID_USUARIO)
    REFERENCES TB_USUARIO(ID),
  FOREIGN KEY(ID_ACTION)
    REFERENCES TB_ACTION(ID));
GO


CREATE INDEX TB_LOG_ACESSO_FKIndex1 ON TB_LOG_ACESSO (ID_USUARIO);
GO
CREATE INDEX TB_LOG_ACESSO_FKIndex2 ON TB_LOG_ACESSO (ID_ACTION);
GO

CREATE INDEX IFK_FK_LOG_ACESSO_USUARIO ON TB_LOG_ACESSO (ID_USUARIO);
GO
CREATE INDEX IFK_FK_LOG_ACESSO_ACTION ON TB_LOG_ACESSO (ID_ACTION);
GO


CREATE TABLE TB_FONTE_DEPARTAMENTO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_FONTE INTEGER  NOT NULL  ,
  ID_DEPARTAMENTO INTEGER  NOT NULL    ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ID_DEPARTAMENTO)
    REFERENCES TB_DEPARTAMENTO_CLIENTE(ID),
  FOREIGN KEY(ID_FONTE)
    REFERENCES TB_FONTE_PAGADORA(ID));
GO


CREATE INDEX TB_FONTE_DEPARTAMENTO_FKIndex1 ON TB_FONTE_DEPARTAMENTO (ID_DEPARTAMENTO);
GO
CREATE INDEX TB_FONTE_DEPARTAMENTO_FKIndex2 ON TB_FONTE_DEPARTAMENTO (ID_FONTE);
GO

CREATE INDEX IFK_FK_FONTE_DEPARTAMENTO ON TB_FONTE_DEPARTAMENTO (ID_DEPARTAMENTO);
GO
CREATE INDEX IFK_FK_FONTE_DEPARTAMENTO_FONT ON TB_FONTE_DEPARTAMENTO (ID_FONTE);
GO


CREATE TABLE TB_MODULO_DEPARTAMENTO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_DEPARTAMENTO INTEGER  NOT NULL  ,
  ID_MODULO INTEGER  NOT NULL  ,
  FLG_ATIVO BIT  NOT NULL    ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_MODULO)
    REFERENCES TB_MODULO(ID),
  FOREIGN KEY(ID_DEPARTAMENTO)
    REFERENCES TB_DEPARTAMENTO_CLIENTE(ID));
GO


CREATE INDEX TB_USUARIO_MODULO_FKIndex2 ON TB_MODULO_DEPARTAMENTO (ID_MODULO);
GO
CREATE INDEX TB_MODULO_DEPARTAMENTO_FKIndex2 ON TB_MODULO_DEPARTAMENTO (ID_DEPARTAMENTO);
GO
CREATE UNIQUE INDEX UK_MODULO_DEPARTAMENTO ON TB_MODULO_DEPARTAMENTO (ID_DEPARTAMENTO, ID_MODULO);
GO

CREATE INDEX IFK_FK_USUARIO_MODULO_MODULO ON TB_MODULO_DEPARTAMENTO (ID_MODULO);
GO
CREATE INDEX IFK_FK_MODULO_DEPARTAMENTO_DEP ON TB_MODULO_DEPARTAMENTO (ID_DEPARTAMENTO);
GO


CREATE TABLE TB_TAREFA (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_USUARIO INTEGER  NOT NULL  ,
  ID_MODULO INTEGER  NOT NULL  ,
  NOM_TAREFA VARCHAR(300)  NOT NULL  ,
  DES_TAREFA VARCHAR(3000)    ,
  FLG_ATIVO BIT  NOT NULL DEFAULT 1   ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ID_USUARIO)
    REFERENCES TB_USUARIO(ID),
  FOREIGN KEY(ID_MODULO)
    REFERENCES TB_MODULO(ID));
GO


CREATE INDEX TB_TAREFA_FKIndex1 ON TB_TAREFA (ID_USUARIO);
GO
CREATE INDEX TB_TAREFA_FKIndex2 ON TB_TAREFA (ID_MODULO);
GO

CREATE INDEX IFK_FK_TAREFA_USUARIO ON TB_TAREFA (ID_USUARIO);
GO
CREATE INDEX IFK_FK_TAREFA_MODULO ON TB_TAREFA (ID_MODULO);
GO


CREATE TABLE TB_TAREFA_FONTE (
  ID INTEGER  NOT NULL  ,
  ID_FONTE_DEPARTAMENTO INTEGER  NOT NULL  ,
  ID_TAREFA INTEGER  NOT NULL  ,
  FLG_ATIVO BIT      ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_TAREFA)
    REFERENCES TB_TAREFA(ID),
  FOREIGN KEY(ID_FONTE_DEPARTAMENTO)
    REFERENCES TB_FONTE_DEPARTAMENTO(ID));
GO


CREATE INDEX UK_TAREFA_FONTE ON TB_TAREFA_FONTE (ID_FONTE_DEPARTAMENTO, ID_TAREFA);
GO
CREATE INDEX TB_TAREFA_FONTE_FKIndex1 ON TB_TAREFA_FONTE (ID_TAREFA);
GO
CREATE INDEX TB_TAREFA_FONTE_FKIndex2 ON TB_TAREFA_FONTE (ID_FONTE_DEPARTAMENTO);
GO

CREATE INDEX IFK_FK_TAREFA_FONTE_TAREFA ON TB_TAREFA_FONTE (ID_TAREFA);
GO
CREATE INDEX IFK_FK_FONTE_TAREFA_FONTE_DEPA ON TB_TAREFA_FONTE (ID_FONTE_DEPARTAMENTO);
GO


CREATE TABLE TB_TAREFA_FONTE_ACESSO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_UNIDADE INTEGER  NOT NULL  ,
  ID_FONTE_PARAMETRO_DEFINICAO INTEGER  NOT NULL  ,
  ID_TAREFA_FONTE INTEGER  NOT NULL  ,
  VAL_ACESSO VARCHAR(2000)  NOT NULL    ,
PRIMARY KEY(ID)        ,
  FOREIGN KEY(ID_TAREFA_FONTE)
    REFERENCES TB_TAREFA_FONTE(ID),
  FOREIGN KEY(ID_UNIDADE)
    REFERENCES TB_UNIDADE(ID),
  FOREIGN KEY(ID_FONTE_PARAMETRO_DEFINICAO)
    REFERENCES TB_FONTE_PAGADORA_PARAMETRO_DEFINICAO(ID));
GO


CREATE INDEX TB_TAREFA_FONTE_ACESSO_FKIndex1 ON TB_TAREFA_FONTE_ACESSO (ID_TAREFA_FONTE);
GO
CREATE INDEX TB_TAREFA_FONTE_ACESSO_FKIndex2 ON TB_TAREFA_FONTE_ACESSO (ID_UNIDADE);
GO
CREATE INDEX TB_TAREFA_FONTE_ACESSO_FKIndex3 ON TB_TAREFA_FONTE_ACESSO (ID_FONTE_PARAMETRO_DEFINICAO);
GO
CREATE UNIQUE INDEX UK_TAREFA_FONTE_ACESSO ON TB_TAREFA_FONTE_ACESSO (ID_UNIDADE, ID_FONTE_PARAMETRO_DEFINICAO, ID_TAREFA_FONTE);
GO

CREATE INDEX IFK_FK_FONTE_ACESSO_TAREFA_FON ON TB_TAREFA_FONTE_ACESSO (ID_TAREFA_FONTE);
GO
CREATE INDEX IFK_FK_TAREFA_FONTE_ACESSO_UNI ON TB_TAREFA_FONTE_ACESSO (ID_UNIDADE);
GO
CREATE INDEX IFK_FK_TAREFA_FONTE_ACESSO_PAR ON TB_TAREFA_FONTE_ACESSO (ID_FONTE_PARAMETRO_DEFINICAO);
GO


CREATE TABLE TB_LOG_SISTEMA (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_ACTION INTEGER  NOT NULL  ,
  ID_MODULO INTEGER  NOT NULL  ,
  ID_USUARIO INTEGER  NOT NULL  ,
  DTH_ACAO DATETIME  NOT NULL  ,
  FLG_ERRO BIT  NOT NULL  ,
  DES_ACAO VARCHAR(8000)  NOT NULL  ,
  NUM_IP VARCHAR(50)      ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_USUARIO)
    REFERENCES TB_USUARIO(ID),
  FOREIGN KEY(ID_MODULO)
    REFERENCES TB_MODULO(ID),
  FOREIGN KEY(ID_ACTION)
    REFERENCES TB_ACTION(ID));
GO


CREATE INDEX TB_LOG_SISTEMA_FKIndex1 ON TB_LOG_SISTEMA (ID_USUARIO);
GO
CREATE INDEX TB_LOG_SISTEMA_FKIndex2 ON TB_LOG_SISTEMA (ID_MODULO);
GO
CREATE INDEX TB_LOG_SISTEMA_FKIndex3 ON TB_LOG_SISTEMA (ID_ACTION);
GO

CREATE INDEX IFK_FK_LOG_SISTEMA_USUARIO ON TB_LOG_SISTEMA (ID_USUARIO);
GO
CREATE INDEX IFK_FK_LOG_ERRO_MODULO ON TB_LOG_SISTEMA (ID_MODULO);
GO
CREATE INDEX IFK_FK_LOG_ERRO_ACTION ON TB_LOG_SISTEMA (ID_ACTION);
GO


CREATE TABLE TB_HISTORICO_EXECUCAO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_TAREFA INTEGER  NOT NULL  ,
  FLG_SUCESSO BIT  NOT NULL  ,
  DES_DETALHE VARCHAR(4000)  NOT NULL  ,
  DTH_EXECUCAO DATETIME  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_TAREFA)
    REFERENCES TB_TAREFA(ID));
GO


CREATE INDEX TB_HISTORICO_EXECUCAO_FKIndex1 ON TB_HISTORICO_EXECUCAO (ID_TAREFA);
GO

CREATE INDEX IFK_FK_HISTORICO_EXECUCAO_TARE ON TB_HISTORICO_EXECUCAO (ID_TAREFA);
GO


CREATE TABLE TB_ACAO (
  ID INTEGER  NOT NULL  ,
  ID_TIPO_ACAO INTEGER  NOT NULL  ,
  ID_TAREFA INTEGER  NOT NULL  ,
  NOM_CAMINHO_APP VARCHAR(1000)  NOT NULL  ,
  DES_ARGUMENTO VARCHAR(4000)    ,
  NUM_ORDEM_EXECUCAO INTEGER  NOT NULL    ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ID_TAREFA)
    REFERENCES TB_TAREFA(ID)
      ON DELETE CASCADE,
  FOREIGN KEY(ID_TIPO_ACAO)
    REFERENCES TB_TIPO_ACAO(ID));
GO


CREATE INDEX TB_ACAO_FKIndex1 ON TB_ACAO (ID_TAREFA);
GO
CREATE INDEX TB_ACAO_FKIndex2 ON TB_ACAO (ID_TIPO_ACAO);
GO

CREATE INDEX IFK_FK_ACAO_TAREFA ON TB_ACAO (ID_TAREFA);
GO
CREATE INDEX IFK_FK_ACAO_TIPO ON TB_ACAO (ID_TIPO_ACAO);
GO


CREATE TABLE TB_TAREFA_TIPO_ENTREGA (
  ID INTEGER  NOT NULL   IDENTITY ,
  TB_TIPO_ENTREGA_ID INTEGER  NOT NULL  ,
  TB_TAREFA_ID INTEGER  NOT NULL    ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(TB_TAREFA_ID)
    REFERENCES TB_TAREFA(ID),
  FOREIGN KEY(TB_TIPO_ENTREGA_ID)
    REFERENCES TB_TIPO_ENTREGA(ID));
GO


CREATE INDEX TB_TAREFA_TIPO_ENTREGA_FKIndex1 ON TB_TAREFA_TIPO_ENTREGA (TB_TAREFA_ID);
GO
CREATE INDEX TB_TAREFA_TIPO_ENTREGA_FKIndex2 ON TB_TAREFA_TIPO_ENTREGA (TB_TIPO_ENTREGA_ID);
GO

CREATE INDEX IFK_Rel_44 ON TB_TAREFA_TIPO_ENTREGA (TB_TAREFA_ID);
GO
CREATE INDEX IFK_Rel_45 ON TB_TAREFA_TIPO_ENTREGA (TB_TIPO_ENTREGA_ID);
GO


CREATE TABLE TB_TAREFA_PROXIMA (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_TAREFA_PROXIMA INTEGER  NOT NULL  ,
  ID_TAREFA_ATUAL INTEGER  NOT NULL    ,
PRIMARY KEY(ID)      ,
  FOREIGN KEY(ID_TAREFA_ATUAL)
    REFERENCES TB_TAREFA(ID),
  FOREIGN KEY(ID_TAREFA_PROXIMA)
    REFERENCES TB_TAREFA(ID));
GO


CREATE INDEX TB_TAREFA_PROXIMA_FKIndex1 ON TB_TAREFA_PROXIMA (ID_TAREFA_ATUAL);
GO
CREATE INDEX TB_TAREFA_PROXIMA_FKIndex2 ON TB_TAREFA_PROXIMA (ID_TAREFA_PROXIMA);
GO
CREATE UNIQUE INDEX UK_TAREFA_PROXIMA ON TB_TAREFA_PROXIMA (ID_TAREFA_PROXIMA, ID_TAREFA_ATUAL);
GO

CREATE INDEX IFK_FK_TAREFA_ATUAL ON TB_TAREFA_PROXIMA (ID_TAREFA_ATUAL);
GO
CREATE INDEX IFK_FK_TAREFA_PROXIMA ON TB_TAREFA_PROXIMA (ID_TAREFA_PROXIMA);
GO


CREATE TABLE TB_DISPARADOR (
  ID INTEGER  NOT NULL  ,
  ID_TIPO_DISPARADOR INT  NOT NULL  ,
  ID_TAREFA INTEGER  NOT NULL  ,
  DTH_INICIO DATETIME  NOT NULL  ,
  DTH_FIM DATETIME    ,
  FLG_DOMINGO BIT    ,
  FLG_SEGUNDA BIT    ,
  FLG_TERCA BIT    ,
  FLG_QUARTA BIT    ,
  FLG_QUINTA BIT    ,
  FLG_SEXTA BIT    ,
  FLG_SABADO BIT    ,
  NUM_REPETICAO INT  NOT NULL DEFAULT 0   ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ID_TAREFA)
    REFERENCES TB_TAREFA(ID)
      ON DELETE CASCADE,
  FOREIGN KEY(ID_TIPO_DISPARADOR)
    REFERENCES TB_TIPO_DISPARADOR(ID));
GO


CREATE INDEX TB_DISPARADORES_FKIndex1 ON TB_DISPARADOR (ID_TAREFA);
GO
CREATE INDEX TB_DISPARADOR_FKIndex2 ON TB_DISPARADOR (ID_TIPO_DISPARADOR);
GO

CREATE INDEX IFK_FK_DISPARADORES_TAREFA ON TB_DISPARADOR (ID_TAREFA);
GO
CREATE INDEX IFK_FK_DISPARADOR_TIPO ON TB_DISPARADOR (ID_TIPO_DISPARADOR);
GO


CREATE TABLE TB_GRUPO_NOTIFICACAO_ACAO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_GRUPO_NOTIFICACAO INTEGER  NOT NULL  ,
  ID_ACAO INTEGER  NOT NULL    ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ID_GRUPO_NOTIFICACAO)
    REFERENCES TB_GRUPO_NOTIFICACAO(ID),
  FOREIGN KEY(ID_ACAO)
    REFERENCES TB_ACAO(ID));
GO


CREATE INDEX TB_GRUPO_NOTIFICACAO_ACAO_FKIndex1 ON TB_GRUPO_NOTIFICACAO_ACAO (ID_GRUPO_NOTIFICACAO);
GO
CREATE INDEX TB_GRUPO_NOTIFICACAO_ACAO_FKIndex2 ON TB_GRUPO_NOTIFICACAO_ACAO (ID_ACAO);
GO

CREATE INDEX IFK_FK_GRUPO_NOTIFICACAO_ACAO_ ON TB_GRUPO_NOTIFICACAO_ACAO (ID_GRUPO_NOTIFICACAO);
GO
CREATE INDEX IFK_FK_ACAO_GRUPO_NOTIFICACAO_ ON TB_GRUPO_NOTIFICACAO_ACAO (ID_ACAO);
GO


CREATE TABLE TB_AGENDA_EXECUCAO (
  ID INTEGER  NOT NULL   IDENTITY ,
  ID_DISPARADOR INTEGER  NOT NULL  ,
  DTH_EXECUCAO DATETIME  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_DISPARADOR)
    REFERENCES TB_DISPARADOR(ID)
      ON DELETE CASCADE);
GO


CREATE INDEX TB_AGENDA_EXECUCAO_FKIndex1 ON TB_AGENDA_EXECUCAO (ID_DISPARADOR);
GO

CREATE INDEX IFK_FK_AGENDA_EXECUCAO_DISPARA ON TB_AGENDA_EXECUCAO (ID_DISPARADOR);
GO


