USE YOUNITY_ONE
GO

IF OBJECT_ID('SP_LOGAR') IS NOT NULL
	DROP PROCEDURE DBO.SP_LOGAR
GO

CREATE PROCEDURE DBO.SP_LOGAR
	@COD_USUARIO VARCHAR(15),
	@DES_SENHA VARCHAR(4000)
AS
BEGIN

	--PERMISSÕES BASEADAS EM UM GRUPO
	SELECT 
		U.COD_USUARIO, u.NOM_USUARIO, G.ID ID_GRUPO, G.DES_GRUPO, A.NOM_ACTION, C.NOM_CONTROLLER
	FROM 
		TB_USUARIO U
		INNER JOIN TB_USUARIO_GRUPO G ON U.ID_GRUPO = G.ID
		INNER JOIN TB_PERMISSOES_GRUPO P ON G.ID = P.ID_GRUPO
		INNER JOIN TB_ACTION A ON P.ID_ACTION = A.ID
		INNER JOIN TB_CONTROLER C ON A.ID_CONTROLLER = C.ID
	WHERE
		U.FLG_ATIVO = 1
		AND U.COD_USUARIO = @COD_USUARIO
		AND U.DES_SENHA = SUBSTRING(sys.fn_sqlvarbasetostr(HASHBYTES('MD5', @DES_SENHA)),3,32)

	UNION

	--PERMISSÕES BASEADAS AVULSAS, INDEPENDENTE DO GRUPO
	SELECT 
		U.COD_USUARIO, u.NOM_USUARIO, 0 ID_GRUPO, 'PERMISSÃO AVULSA' DES_GRUPO, A.NOM_ACTION, C.NOM_CONTROLLER
	FROM 
		TB_USUARIO U
		INNER JOIN TB_USUARIO_ACTION UA ON U.ID = UA.ID_USUARIO
		INNER JOIN TB_ACTION A ON UA.ID_ACTION = A.ID
		INNER JOIN TB_CONTROLER C ON A.ID_CONTROLLER = C.ID
	WHERE
		U.FLG_ATIVO = 1
		AND U.COD_USUARIO = @COD_USUARIO
		AND U.DES_SENHA = SUBSTRING(sys.fn_sqlvarbasetostr(HASHBYTES('MD5', @DES_SENHA)),3,32)

END