USE YOUNITY_ONE
GO

IF OBJECT_ID('SP_LOGAR') IS NOT NULL
	DROP PROCEDURE DBO.SP_LOGAR
GO

CREATE PROCEDURE DBO.SP_LOGAR
	@COD_USUARIO VARCHAR(15),
	@DES_SENHA VARCHAR(4000)
AS
BEGIN

	SELECT 
		U.COD_USUARIO, G.ID ID_GRUPO, G.DES_GRUPO, A.NOM_ACTION, C.NOM_CONTROLLER
	FROM 
		TB_USUARIO U
		INNER JOIN TB_USUARIO_GRUPO G ON U.ID_GRUPO = G.ID
		INNER JOIN TB_PERMISSOES_GRUPO P ON G.ID = P.ID_GRUPO
		INNER JOIN TB_ACTION A ON P.ID_ACTION = A.ID
		INNER JOIN TB_CONTROLER C ON A.ID_CONTROLLER = C.ID
	WHERE
		U.FLG_ATIVO = 1
		AND U.COD_USUARIO = @COD_USUARIO
		AND U.DES_SENHA = @DES_SENHA

END